### ISSUE TITLE
Missing `#include <vector>` in `CsvIO.h`

### ISSUE THREAD

**Issue by fuyw** [david830wu/WCCommon#1]
Fail to install WCCommon on my computer without adding `#include <vector>` in `CsvIO.h`.

An error of `implicit instantiation of undefined template` for:

https://github.com/david830wu/WCCommon/blob/2775e68fbbb68a1a4f5202d0c1ec8b03161b6e0e/include/CsvIO.h#L249

**Comment by david830wu** [comment]
Solved
